- queue/Examination_queue.java
Example java code to indicate priority queue
> Priority-queue

- stack/stackArrayapp.java
Implementation of stack data structure using arrays. the corresponding programming language is java.
> Implementing stack DS using arrays

- Tree/PairSumBST.java
Given a Balanced Binary Search Tree and a target sum, write a function that returns true if there is a pair with a sum equal to the target sum, otherwise return false. The expected time complexity is O(n) and only O(Logn) extra space can be used. Any modification to the Binary Search Tree is not allowed. Note that the height of a Balanced BST is always O(Logn).
[Link to the problem](https://www.geeksforgeeks.org/find-a-pair-with-given-sum-in-bst/)
> Added pairsum problem on BST

- Tree/LowestCommonANcestor .java
Problem Statement:
Given a binary tree, find the lowest common ancestor (LCA) of two given nodes in the tree.
According to the [definition of LCA on Wikipedia](https://en.wikipedia.org/wiki/Lowest_common_ancestor): “The lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants (where we allow a node to be a descendant of itself).”
[Question link](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/)
> ADDED Lowest Common ancestor sum

- Matrix/SpiralMatrix.java
This problem displays the matrix elements in spiral order.
> Spiral Matrix Solution in Java added

- cpp_codes/Balance_paranthesis.cpp
- cpp_codes/codechef even subset xor.cpp
- cpp_codes/substring of binary.cpp
- recursion/findCombination.cpp
#40 
Dsa question added :  Substring of Binary , Even Subset xor , Balance paranthesis , Find Combination
> Dsa question :  Substring of Binary , Even Subset xor , Balance paranthesis , Find Combination

- cpp_codes/leetcode : 78 : subset.cpp
- cpp_codes/leetcode-47-permutation2.cpp
- cpp_codes/leetcode-905-sortbyParity.cpp
- cpp_codes/longestIncPath.cpp
- cpp_codes/square_root_BS.cpp
- cpp_codes/topologicalSort.cpp
#40 
Dsa question : Square root using Binary Search, Longest Path , Sort by parity , Subsets, Permutation
> Dsa question : Square root using Binary Search, Longest Path , Sort by parity , Subsets, Permutation 

- SortingAndSearching/TernarySearch.java
Ternary Search is an optimized code of Binary search, which reduces Binary Search's complexity of Log N base 2 to Log N base 3. Fast for Huge inputs.
> added Ternary Search algorithm

- DynamicProgramming/Best_Time_to_buy_stock_with_fee.cpp
- Tree/vertical_order_traversal.cpp
- cpp_codes/min_moves_to_make_equal_array.cpp
#40 
questions : vertical order traversal , minimum moves to makes a equal array and stock buy with Transaction fees
> vertical order traversal , minimum moves to makes a equal array and stock buy with Transaction fees 

- DynamicProgramming/frogJump.java
frog consumes some energy to jump from one step to another. return the minimum energy that can be used by the frog to jump from stair 0 to stair N-1.
> 0 to n stairs and a frog

- DynamicProgramming/PartitionToKEqualSumSubsets.java
> Created partition to k equal sum subsets java

- LinkedListPackage/finding middleElement_LL.java
- LinkedListPackage/middleElement_LL.java
@sourav2002 i have added this algo  , which is helping to find middle element in linked list  Please accept my PULL request.
> Create finding middleElement_LL.java

- README.md
Added description in  ``` Readme.md``` . 
issue closed #51
> added description of the data structure

- Tree/BinaryTreeImplementation.java
Complete Basic Binary Tree Implementation
> Java Program to Implement Binary Tree

- recursion/SudokuSolver.cpp
Sudoku Solver is a recursive code based on Backtracking algo.
> Created Sudoku Solver code on recursion.

- SortingAndSearching/Z_Algorithm.java
Z Algorithm is a famous algorithm for pattern finding.
> Added Z Algorithm in java

- array/Dutch_National_flag_algorithm.java
Language - Java
Author - mdrashidmeraj
solution - It is a programming problem proposed by Edsger Dijkstra. The flag of the Netherlands consists of three colours: white, red, and blue. The task is to randomly arrange balls of white, red, and blue so that balls of the same colour are placed together. For DNF (Dutch National Flag), we sort an array of 0, 1, and 2's in linear time that does not consume any extra space.
> Dutch National flag algorithm

- stack/double_stack.c
- stack/infix to prefix.cpp
- stack/multiple_paranthrsis_using_stacks.c
- stack/parantheis_matching_using_stacks.c
- stack/stack_using_Linked_list.c
- stack/stacks_operations.c
Hi guys as you know, stacks is an abstract data type which is used for various purpose , i have added some applications of stacks and also the basic operations of stacks.
Hope this helps you guys , thank you!
> Contribute Applications of stacks 

- DynamicProgramming/UniquePaths.java
This is a DP Medium level question solved using memoization technique.
> UniquePaths.java

- stack/Palindrome Stack String.c
Reversing and also checking whether a string is a palindrome or not
> Create Palindrome Stack String.c

- BitManipulation/AllDistinctSubsetsOfGivenSet.java
Printing all distinct Subsets of a given Set using Bit Manipulation.
> All distinct subsets of given set using Bit Manipulation

- array/SortAnArray.java
Solution for LeetCode Probelm no.912 in java.
Given an array of integers nums, sort the array in ascending order and return it.
You must solve the problem without using any built-in functions in O(nlog(n)) time complexity and with the smallest space complexity possible.
Input: nums = [5,2,3,1]
Output: [1,2,3,5]
Explanation: After sorting the array, the positions of some numbers are not changed (for example, 2 and 3), while the positions of other numbers are changed (for example, 1 and 5).
> Added Sort_An_Array #LeetCode912 in JAVA.

- Heap/Kth largest element in an array
- Heap/Merge K Sorted
- Heap/Sliding Window Maximum
- Tree/Symmetric tree
Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).
> Create Symmetric tree
